{{- if and .Values.controller.enabled .Values.controller.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "node-doctor.controller.name" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-doctor.controller.labels" . | nindent 4 }}
  {{- with .Values.controller.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.controller.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.controller.persistence.size }}
  {{- if .Values.controller.persistence.storageClassName }}
  storageClassName: {{ .Values.controller.persistence.storageClassName }}
  {{- end }}
{{- end }}
