# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # Global coverage thresholds
  precision: 2
  round: down
  range: "70...100"

  status:
    # Project-level coverage (overall repository)
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error

    # Patch-level coverage (only changed lines in PR)
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Ignore certain paths from coverage
ignore:
  - "**/*_test.go"
  - "**/test/**"
  - "**/testdata/**"
  - "docs/**"
  - "deployment/**"
  - "helm/**"

# Flag management
flags:
  unittests:
    paths:
      - pkg/
      - cmd/
    carryforward: true
