---
# Source: node-doctor/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-doctor
  namespace: node-doctor
  labels:
    helm.sh/chart: node-doctor-1.0.0
    app.kubernetes.io/name: node-doctor
    app.kubernetes.io/instance: node-doctor
    app: node-doctor
    component: monitoring
    tier: system
    app.kubernetes.io/version: "v1.0.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: monitoring
    tier: system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-doctor
      app.kubernetes.io/instance: node-doctor
      app: node-doctor
      component: monitoring
      tier: system
  namespaceSelector:
    matchNames:
      - node-doctor
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true

